### ISSUE TITLE
telemetry and location examples did not completely quit on Windows

### ISSUE THREAD

**Issue by mafoglia** [Wind-River/device-cloud-python#143] opened 2017-11-24 16:29 UTC
(This could be difficult to reproduce.  I've gone through same scenario a number of times and this is the first time experiencing this behavior.)

After running the "Quit App" method from IoT console for iot-simple-[telemetry|location].py, both apps remain connected.  The console traffic(from cmd windows) is attached and one can see that the quit message is received but the exit handshaking does not complete for either app.

In this same time frame, the "Quit App" method was also run on the iot-simple-actions.py example, and this one exited correctly.  Console is also attached.

This is running on Win10 Home with Python 3.6.2.  The location and telemetry apps had been sending data for the last two days.  

[simple-location-console.log.txt](https://github.com/Wind-River/device-cloud-python/files/1502156/simple-location-console.log.txt)
[simple-telemetry-console.log.txt](https://github.com/Wind-River/device-cloud-python/files/1502157/simple-telemetry-console.log.txt)
[simple-actions-console.log.txt](https://github.com/Wind-River/device-cloud-python/files/1502158/simple-actions-console.log.txt)

**Comment by element-82** [comment] 2017-12-04 19:12
Unable to reproduce issue.  Closing.  Reopen if you see the issue again.

**Closed by element-82** 2017-12-04 19:12 UTC
Labels: can't reproduce
